### ISSUE TITLE
Bro, how it use?

### ISSUE THREAD

**Issue by FlikeID** [AriWD40/Godot-SMTP-Gmail#3]
Hi, could you add a couple of examples of sending emails using this script

**Comment by AriWD40** [comment]
I don't do this a lot. I wrote this because there were so few sources online and I got so frustrated with the lack of dovumentation, hacking through it myself. I decided to help out and make the world slightly better.

I will never revisit this, sorry. I live a busy life. Im not sure if gmail even still supports this. Good luck though

**Comment by FlikeID** [comment]
Thanks for the answer, by the way
